version: '3.9'
services:
  rtmp:
    build: ./rtmp
    ports:
      - "1935:1935"
      - "8081:8081"
    container_name: rtmp_server

  rtmp_proxy:
    build: ./rtmp_proxy
    ports:
      - "5001:5001"
    depends_on:
      - rtmp
    container_name: rtmp_proxy

  api-service:
    build: ./api-service
    container_name: livestream-api-service